// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

type OrderItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuItemId int64   `protobuf:"varint,1,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	Name       string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity   int32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price      float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *OrderItem) Reset()         { *x = OrderItem{} }
func (x *OrderItem) String() string { return protoimpl.X.MessageStringOf(x) }
func (*OrderItem) ProtoMessage()    {}
func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (x *OrderItem) GetMenuItemId() int64   { return x.MenuItemId }
func (x *OrderItem) GetName() string        { return x.Name }
func (x *OrderItem) GetQuantity() int32     { return x.Quantity }
func (x *OrderItem) GetPrice() float64      { return x.Price }

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       int64       `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RestaurantId int64       `protobuf:"varint,3,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Items        []*OrderItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Status       string      `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Total        float64     `protobuf:"fixed64,6,opt,name=total,proto3" json:"total,omitempty"`
	CreatedAt    string      `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    string      `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Order) Reset()         { *x = Order{} }
func (x *Order) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Order) ProtoMessage()    {}
func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (x *Order) GetId() int64            { return x.Id }
func (x *Order) GetUserId() int64        { return x.UserId }
func (x *Order) GetRestaurantId() int64  { return x.RestaurantId }
func (x *Order) GetItems() []*OrderItem  { return x.Items }
func (x *Order) GetStatus() string       { return x.Status }
func (x *Order) GetTotal() float64       { return x.Total }
func (x *Order) GetCreatedAt() string    { return x.CreatedAt }
func (x *Order) GetUpdatedAt() string    { return x.UpdatedAt }

type Payment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId int64   `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status  string  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Amount  float64 `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Method  string  `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
}

func (x *Payment) Reset()         { *x = Payment{} }
func (x *Payment) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Payment) ProtoMessage()    {}
func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (x *Payment) GetId() int64      { return x.Id }
func (x *Payment) GetOrderId() int64 { return x.OrderId }
func (x *Payment) GetStatus() string { return x.Status }
func (x *Payment) GetAmount() float64 { return x.Amount }
func (x *Payment) GetMethod() string { return x.Method }

type CreateOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64        `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RestaurantId int64        `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Items        []*OrderItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CreateOrderRequest) Reset()         { *x = CreateOrderRequest{} }
func (x *CreateOrderRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (x *CreateOrderRequest) GetUserId() int64        { return x.UserId }
func (x *CreateOrderRequest) GetRestaurantId() int64  { return x.RestaurantId }
func (x *CreateOrderRequest) GetItems() []*OrderItem  { return x.Items }

type OrderIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId int64 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *OrderIdRequest) Reset()         { *x = OrderIdRequest{} }
func (x *OrderIdRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*OrderIdRequest) ProtoMessage()    {}
func (x *OrderIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (x *OrderIdRequest) GetOrderId() int64 { return x.OrderId }

type UserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *UserIdRequest) Reset()         { *x = UserIdRequest{} }
func (x *UserIdRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UserIdRequest) ProtoMessage()    {}
func (x *UserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (x *UserIdRequest) GetUserId() int64 { return x.UserId }

type UpdateStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId int64  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateStatusRequest) Reset()         { *x = UpdateStatusRequest{} }
func (x *UpdateStatusRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpdateStatusRequest) ProtoMessage()    {}
func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (x *UpdateStatusRequest) GetOrderId() int64  { return x.OrderId }
func (x *UpdateStatusRequest) GetStatus() string  { return x.Status }

type OrderList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *OrderList) Reset()         { *x = OrderList{} }
func (x *OrderList) String() string { return protoimpl.X.MessageStringOf(x) }
func (*OrderList) ProtoMessage()    {}
func (x *OrderList) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (x *OrderList) GetOrders() []*Order { return x.Orders }

type PaymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId int64   `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Method  string  `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Amount  float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *PaymentRequest) Reset()         { *x = PaymentRequest{} }
func (x *PaymentRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*PaymentRequest) ProtoMessage()    {}
func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (x *PaymentRequest) GetOrderId() int64  { return x.OrderId }
func (x *PaymentRequest) GetMethod() string  { return x.Method }
func (x *PaymentRequest) GetAmount() float64 { return x.Amount }

type PaymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payment *Payment `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	Success bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PaymentResponse) Reset()         { *x = PaymentResponse{} }
func (x *PaymentResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*PaymentResponse) ProtoMessage()    {}
func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (x *PaymentResponse) GetPayment() *Payment { return x.Payment }
func (x *PaymentResponse) GetSuccess() bool     { return x.Success }

type CartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*OrderItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CartRequest) Reset()         { *x = CartRequest{} }
func (x *CartRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CartRequest) ProtoMessage()    {}
func (x *CartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (x *CartRequest) GetItems() []*OrderItem { return x.Items }

type TotalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subtotal    float64 `protobuf:"fixed64,1,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	DeliveryFee float64 `protobuf:"fixed64,2,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	Total       float64 `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *TotalResponse) Reset()         { *x = TotalResponse{} }
func (x *TotalResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*TotalResponse) ProtoMessage()    {}
func (x *TotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (x *TotalResponse) GetSubtotal() float64    { return x.Subtotal }
func (x *TotalResponse) GetDeliveryFee() float64 { return x.DeliveryFee }
func (x *TotalResponse) GetTotal() float64       { return x.Total }

// ── registry (minimal, enough for grpc to work) ───────────────────────────────

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 12)

var _ = sync.Once{}
var _ = reflect.TypeOf

func init() {
	// Types are registered lazily via ProtoReflect(); no explicit init needed
	// for runtime usage. Full rawDesc registration is done by protoc-gen-go
	// when you run `make proto` — see Makefile.
}
