@baseUrl = http://localhost:8080
@contentType = application/json
@accessToken = <paste_access_token_here>
@deliveryId = 1
@driverId = 1


### 1. Assign driver to order
POST {{baseUrl}}/api/delivery/assign
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "order_id": 1,
  "user_id": 1,
  "user_email": "nikita@example.com",
  "delivery_address": "Abay 10, Almaty"
}


### 2. Track delivery (polling)
GET {{baseUrl}}/api/delivery/{{deliveryId}}/track
Authorization: Bearer {{accessToken}}


### 3. Get delivery details
GET {{baseUrl}}/api/delivery/{{deliveryId}}
Authorization: Bearer {{accessToken}}


### 4. Update driver location
PATCH {{baseUrl}}/api/delivery/location
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "driver_id": {{driverId}},
  "latitude": 43.238949,
  "longitude": 76.889709
}


### 5. List driver's deliveries
GET {{baseUrl}}/api/delivery/drivers/{{driverId}}
Authorization: Bearer {{accessToken}}


### 6. Get my delivery history
GET {{baseUrl}}/api/delivery/history
Authorization: Bearer {{accessToken}}


### 7. Complete delivery
POST {{baseUrl}}/api/delivery/{{deliveryId}}/complete
Authorization: Bearer {{accessToken}}


### 8. Cancel delivery
POST {{baseUrl}}/api/delivery/{{deliveryId}}/cancel
Authorization: Bearer {{accessToken}}