// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: delivery.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId          int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail       string                 `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	DeliveryAddress string                 `protobuf:"bytes,4,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssignRequest) Reset() {
	*x = AssignRequest{}
	mi := &file_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRequest) ProtoMessage() {}

func (x *AssignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRequest.ProtoReflect.Descriptor instead.
func (*AssignRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *AssignRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AssignRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssignRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *AssignRequest) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

type DeliveryIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    int64                  `protobuf:"varint,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryIdRequest) Reset() {
	*x = DeliveryIdRequest{}
	mi := &file_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryIdRequest) ProtoMessage() {}

func (x *DeliveryIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryIdRequest.ProtoReflect.Descriptor instead.
func (*DeliveryIdRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryIdRequest) GetDeliveryId() int64 {
	if x != nil {
		return x.DeliveryId
	}
	return 0
}

type DriverIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverIdRequest) Reset() {
	*x = DriverIdRequest{}
	mi := &file_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverIdRequest) ProtoMessage() {}

func (x *DriverIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverIdRequest.ProtoReflect.Descriptor instead.
func (*DriverIdRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *DriverIdRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type UserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdRequest) Reset() {
	*x = UserIdRequest{}
	mi := &file_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdRequest) ProtoMessage() {}

func (x *UserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdRequest.ProtoReflect.Descriptor instead.
func (*UserIdRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *UserIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationRequest) Reset() {
	*x = LocationRequest{}
	mi := &file_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationRequest) ProtoMessage() {}

func (x *LocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationRequest.ProtoReflect.Descriptor instead.
func (*LocationRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *LocationRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *LocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Delivery struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId       int64                  `protobuf:"varint,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	OrderId          int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId           int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail        string                 `protobuf:"bytes,4,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	DriverId         int64                  `protobuf:"varint,5,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DriverName       string                 `protobuf:"bytes,6,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	DriverEmail      string                 `protobuf:"bytes,7,opt,name=driver_email,json=driverEmail,proto3" json:"driver_email,omitempty"`
	DriverPhone      string                 `protobuf:"bytes,8,opt,name=driver_phone,json=driverPhone,proto3" json:"driver_phone,omitempty"`
	Status           string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	DeliveryAddress  string                 `protobuf:"bytes,10,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AssignedAt       string                 `protobuf:"bytes,13,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	CompletedAt      string                 `protobuf:"bytes,14,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CurrentLatitude  float64                `protobuf:"fixed64,15,opt,name=current_latitude,json=currentLatitude,proto3" json:"current_latitude,omitempty"`
	CurrentLongitude float64                `protobuf:"fixed64,16,opt,name=current_longitude,json=currentLongitude,proto3" json:"current_longitude,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *Delivery) GetDeliveryId() int64 {
	if x != nil {
		return x.DeliveryId
	}
	return 0
}

func (x *Delivery) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Delivery) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Delivery) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *Delivery) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *Delivery) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *Delivery) GetDriverEmail() string {
	if x != nil {
		return x.DriverEmail
	}
	return ""
}

func (x *Delivery) GetDriverPhone() string {
	if x != nil {
		return x.DriverPhone
	}
	return ""
}

func (x *Delivery) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Delivery) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *Delivery) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Delivery) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Delivery) GetAssignedAt() string {
	if x != nil {
		return x.AssignedAt
	}
	return ""
}

func (x *Delivery) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *Delivery) GetCurrentLatitude() float64 {
	if x != nil {
		return x.CurrentLatitude
	}
	return 0
}

func (x *Delivery) GetCurrentLongitude() float64 {
	if x != nil {
		return x.CurrentLongitude
	}
	return 0
}

type DeliveryStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId       int64                  `protobuf:"varint,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	DriverName       string                 `protobuf:"bytes,3,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	CurrentLatitude  float64                `protobuf:"fixed64,4,opt,name=current_latitude,json=currentLatitude,proto3" json:"current_latitude,omitempty"`
	CurrentLongitude float64                `protobuf:"fixed64,5,opt,name=current_longitude,json=currentLongitude,proto3" json:"current_longitude,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeliveryStatus) Reset() {
	*x = DeliveryStatus{}
	mi := &file_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryStatus) ProtoMessage() {}

func (x *DeliveryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryStatus.ProtoReflect.Descriptor instead.
func (*DeliveryStatus) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *DeliveryStatus) GetDeliveryId() int64 {
	if x != nil {
		return x.DeliveryId
	}
	return 0
}

func (x *DeliveryStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeliveryStatus) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *DeliveryStatus) GetCurrentLatitude() float64 {
	if x != nil {
		return x.CurrentLatitude
	}
	return 0
}

func (x *DeliveryStatus) GetCurrentLongitude() float64 {
	if x != nil {
		return x.CurrentLongitude
	}
	return 0
}

func (x *DeliveryStatus) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DeliveryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*Delivery            `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryList) Reset() {
	*x = DeliveryList{}
	mi := &file_delivery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryList) ProtoMessage() {}

func (x *DeliveryList) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryList.ProtoReflect.Descriptor instead.
func (*DeliveryList) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{7}
}

func (x *DeliveryList) GetDeliveries() []*Delivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_delivery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{8}
}

type RegisterDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDriverRequest) Reset() {
	*x = RegisterDriverRequest{}
	mi := &file_delivery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDriverRequest) ProtoMessage() {}

func (x *RegisterDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDriverRequest.ProtoReflect.Descriptor instead.
func (*RegisterDriverRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterDriverRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterDriverRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterDriverRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type AvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityRequest) Reset() {
	*x = AvailabilityRequest{}
	mi := &file_delivery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityRequest) ProtoMessage() {}

func (x *AvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityRequest.ProtoReflect.Descriptor instead.
func (*AvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{10}
}

func (x *AvailabilityRequest) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type DriverProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,5,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverProfile) Reset() {
	*x = DriverProfile{}
	mi := &file_delivery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverProfile) ProtoMessage() {}

func (x *DriverProfile) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverProfile.ProtoReflect.Descriptor instead.
func (*DriverProfile) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{11}
}

func (x *DriverProfile) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DriverProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DriverProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DriverProfile) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_delivery_proto protoreflect.FileDescriptor

const file_delivery_proto_rawDesc = "" +
	"\n" +
	"\x0edelivery.proto\x12\bdelivery\"\x8d\x01\n" +
	"\rAssignRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x03 \x01(\tR\tuserEmail\x12)\n" +
	"\x10delivery_address\x18\x04 \x01(\tR\x0fdeliveryAddress\"4\n" +
	"\x11DeliveryIdRequest\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\x03R\n" +
	"deliveryId\".\n" +
	"\x0fDriverIdRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\"(\n" +
	"\rUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"h\n" +
	"\x0fLocationRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"\x9f\x04\n" +
	"\bDelivery\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\x03R\n" +
	"deliveryId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x04 \x01(\tR\tuserEmail\x12\x1b\n" +
	"\tdriver_id\x18\x05 \x01(\x03R\bdriverId\x12\x1f\n" +
	"\vdriver_name\x18\x06 \x01(\tR\n" +
	"driverName\x12!\n" +
	"\fdriver_email\x18\a \x01(\tR\vdriverEmail\x12!\n" +
	"\fdriver_phone\x18\b \x01(\tR\vdriverPhone\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12)\n" +
	"\x10delivery_address\x18\n" +
	" \x01(\tR\x0fdeliveryAddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vassigned_at\x18\r \x01(\tR\n" +
	"assignedAt\x12!\n" +
	"\fcompleted_at\x18\x0e \x01(\tR\vcompletedAt\x12)\n" +
	"\x10current_latitude\x18\x0f \x01(\x01R\x0fcurrentLatitude\x12+\n" +
	"\x11current_longitude\x18\x10 \x01(\x01R\x10currentLongitude\"\xe1\x01\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\x03R\n" +
	"deliveryId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vdriver_name\x18\x03 \x01(\tR\n" +
	"driverName\x12)\n" +
	"\x10current_latitude\x18\x04 \x01(\x01R\x0fcurrentLatitude\x12+\n" +
	"\x11current_longitude\x18\x05 \x01(\x01R\x10currentLongitude\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"B\n" +
	"\fDeliveryList\x122\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2\x12.delivery.DeliveryR\n" +
	"deliveries\"\a\n" +
	"\x05Empty\"W\n" +
	"\x15RegisterDriverRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"3\n" +
	"\x13AvailabilityRequest\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\"\x8f\x01\n" +
	"\rDriverProfile\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12!\n" +
	"\fis_available\x18\x05 \x01(\bR\visAvailable2\x84\x06\n" +
	"\x0fDeliveryService\x12;\n" +
	"\fAssignDriver\x12\x17.delivery.AssignRequest\x1a\x12.delivery.Delivery\x12>\n" +
	"\vGetDelivery\x12\x1b.delivery.DeliveryIdRequest\x1a\x12.delivery.Delivery\x12B\n" +
	"\x14UpdateDriverLocation\x12\x19.delivery.LocationRequest\x1a\x0f.delivery.Empty\x12F\n" +
	"\rTrackDelivery\x12\x1b.delivery.DeliveryIdRequest\x1a\x18.delivery.DeliveryStatus\x12C\n" +
	"\x10CompleteDelivery\x12\x1b.delivery.DeliveryIdRequest\x1a\x12.delivery.Delivery\x12I\n" +
	"\x14ListDriverDeliveries\x12\x19.delivery.DriverIdRequest\x1a\x16.delivery.DeliveryList\x12E\n" +
	"\x12GetDeliveryHistory\x12\x17.delivery.UserIdRequest\x1a\x16.delivery.DeliveryList\x12A\n" +
	"\x0eCancelDelivery\x12\x1b.delivery.DeliveryIdRequest\x1a\x12.delivery.Delivery\x12J\n" +
	"\x0eRegisterDriver\x12\x1f.delivery.RegisterDriverRequest\x1a\x17.delivery.DriverProfile\x127\n" +
	"\vGetMyDriver\x12\x0f.delivery.Empty\x1a\x17.delivery.DriverProfile\x12I\n" +
	"\x0fSetAvailability\x12\x1d.delivery.AvailabilityRequest\x1a\x17.delivery.DriverProfileB)Z'food-delivery/delivery-service/proto/pbb\x06proto3"

var (
	file_delivery_proto_rawDescOnce sync.Once
	file_delivery_proto_rawDescData []byte
)

func file_delivery_proto_rawDescGZIP() []byte {
	file_delivery_proto_rawDescOnce.Do(func() {
		file_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_proto_rawDesc), len(file_delivery_proto_rawDesc)))
	})
	return file_delivery_proto_rawDescData
}

var file_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_delivery_proto_goTypes = []any{
	(*AssignRequest)(nil),         // 0: delivery.AssignRequest
	(*DeliveryIdRequest)(nil),     // 1: delivery.DeliveryIdRequest
	(*DriverIdRequest)(nil),       // 2: delivery.DriverIdRequest
	(*UserIdRequest)(nil),         // 3: delivery.UserIdRequest
	(*LocationRequest)(nil),       // 4: delivery.LocationRequest
	(*Delivery)(nil),              // 5: delivery.Delivery
	(*DeliveryStatus)(nil),        // 6: delivery.DeliveryStatus
	(*DeliveryList)(nil),          // 7: delivery.DeliveryList
	(*Empty)(nil),                 // 8: delivery.Empty
	(*RegisterDriverRequest)(nil), // 9: delivery.RegisterDriverRequest
	(*AvailabilityRequest)(nil),   // 10: delivery.AvailabilityRequest
	(*DriverProfile)(nil),         // 11: delivery.DriverProfile
}
var file_delivery_proto_depIdxs = []int32{
	5,  // 0: delivery.DeliveryList.deliveries:type_name -> delivery.Delivery
	0,  // 1: delivery.DeliveryService.AssignDriver:input_type -> delivery.AssignRequest
	1,  // 2: delivery.DeliveryService.GetDelivery:input_type -> delivery.DeliveryIdRequest
	4,  // 3: delivery.DeliveryService.UpdateDriverLocation:input_type -> delivery.LocationRequest
	1,  // 4: delivery.DeliveryService.TrackDelivery:input_type -> delivery.DeliveryIdRequest
	1,  // 5: delivery.DeliveryService.CompleteDelivery:input_type -> delivery.DeliveryIdRequest
	2,  // 6: delivery.DeliveryService.ListDriverDeliveries:input_type -> delivery.DriverIdRequest
	3,  // 7: delivery.DeliveryService.GetDeliveryHistory:input_type -> delivery.UserIdRequest
	1,  // 8: delivery.DeliveryService.CancelDelivery:input_type -> delivery.DeliveryIdRequest
	9,  // 9: delivery.DeliveryService.RegisterDriver:input_type -> delivery.RegisterDriverRequest
	8,  // 10: delivery.DeliveryService.GetMyDriver:input_type -> delivery.Empty
	10, // 11: delivery.DeliveryService.SetAvailability:input_type -> delivery.AvailabilityRequest
	5,  // 12: delivery.DeliveryService.AssignDriver:output_type -> delivery.Delivery
	5,  // 13: delivery.DeliveryService.GetDelivery:output_type -> delivery.Delivery
	8,  // 14: delivery.DeliveryService.UpdateDriverLocation:output_type -> delivery.Empty
	6,  // 15: delivery.DeliveryService.TrackDelivery:output_type -> delivery.DeliveryStatus
	5,  // 16: delivery.DeliveryService.CompleteDelivery:output_type -> delivery.Delivery
	7,  // 17: delivery.DeliveryService.ListDriverDeliveries:output_type -> delivery.DeliveryList
	7,  // 18: delivery.DeliveryService.GetDeliveryHistory:output_type -> delivery.DeliveryList
	5,  // 19: delivery.DeliveryService.CancelDelivery:output_type -> delivery.Delivery
	11, // 20: delivery.DeliveryService.RegisterDriver:output_type -> delivery.DriverProfile
	11, // 21: delivery.DeliveryService.GetMyDriver:output_type -> delivery.DriverProfile
	11, // 22: delivery.DeliveryService.SetAvailability:output_type -> delivery.DriverProfile
	12, // [12:23] is the sub-list for method output_type
	1,  // [1:12] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_delivery_proto_init() }
func file_delivery_proto_init() {
	if File_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_proto_rawDesc), len(file_delivery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_proto_goTypes,
		DependencyIndexes: file_delivery_proto_depIdxs,
		MessageInfos:      file_delivery_proto_msgTypes,
	}.Build()
	File_delivery_proto = out.File
	file_delivery_proto_goTypes = nil
	file_delivery_proto_depIdxs = nil
}
