// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: delivery.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeliveryService_AssignDriver_FullMethodName         = "/delivery.DeliveryService/AssignDriver"
	DeliveryService_GetDelivery_FullMethodName          = "/delivery.DeliveryService/GetDelivery"
	DeliveryService_UpdateDriverLocation_FullMethodName = "/delivery.DeliveryService/UpdateDriverLocation"
	DeliveryService_TrackDelivery_FullMethodName        = "/delivery.DeliveryService/TrackDelivery"
	DeliveryService_CompleteDelivery_FullMethodName     = "/delivery.DeliveryService/CompleteDelivery"
	DeliveryService_ListDriverDeliveries_FullMethodName = "/delivery.DeliveryService/ListDriverDeliveries"
	DeliveryService_GetDeliveryHistory_FullMethodName   = "/delivery.DeliveryService/GetDeliveryHistory"
	DeliveryService_CancelDelivery_FullMethodName       = "/delivery.DeliveryService/CancelDelivery"
	DeliveryService_RegisterDriver_FullMethodName       = "/delivery.DeliveryService/RegisterDriver"
	DeliveryService_GetMyDriver_FullMethodName          = "/delivery.DeliveryService/GetMyDriver"
)

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliveryServiceClient interface {
	AssignDriver(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*Delivery, error)
	GetDelivery(ctx context.Context, in *DeliveryIdRequest, opts ...grpc.CallOption) (*Delivery, error)
	UpdateDriverLocation(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*Empty, error)
	TrackDelivery(ctx context.Context, in *DeliveryIdRequest, opts ...grpc.CallOption) (*DeliveryStatus, error)
	CompleteDelivery(ctx context.Context, in *DeliveryIdRequest, opts ...grpc.CallOption) (*Delivery, error)
	ListDriverDeliveries(ctx context.Context, in *DriverIdRequest, opts ...grpc.CallOption) (*DeliveryList, error)
	GetDeliveryHistory(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*DeliveryList, error)
	CancelDelivery(ctx context.Context, in *DeliveryIdRequest, opts ...grpc.CallOption) (*Delivery, error)
	RegisterDriver(ctx context.Context, in *RegisterDriverRequest, opts ...grpc.CallOption) (*DriverProfile, error)
	GetMyDriver(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DriverProfile, error)
}

type deliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryServiceClient(cc grpc.ClientConnInterface) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) AssignDriver(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*Delivery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Delivery)
	err := c.cc.Invoke(ctx, DeliveryService_AssignDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetDelivery(ctx context.Context, in *DeliveryIdRequest, opts ...grpc.CallOption) (*Delivery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Delivery)
	err := c.cc.Invoke(ctx, DeliveryService_GetDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) UpdateDriverLocation(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeliveryService_UpdateDriverLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) TrackDelivery(ctx context.Context, in *DeliveryIdRequest, opts ...grpc.CallOption) (*DeliveryStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryStatus)
	err := c.cc.Invoke(ctx, DeliveryService_TrackDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) CompleteDelivery(ctx context.Context, in *DeliveryIdRequest, opts ...grpc.CallOption) (*Delivery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Delivery)
	err := c.cc.Invoke(ctx, DeliveryService_CompleteDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) ListDriverDeliveries(ctx context.Context, in *DriverIdRequest, opts ...grpc.CallOption) (*DeliveryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryList)
	err := c.cc.Invoke(ctx, DeliveryService_ListDriverDeliveries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetDeliveryHistory(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*DeliveryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryList)
	err := c.cc.Invoke(ctx, DeliveryService_GetDeliveryHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) CancelDelivery(ctx context.Context, in *DeliveryIdRequest, opts ...grpc.CallOption) (*Delivery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Delivery)
	err := c.cc.Invoke(ctx, DeliveryService_CancelDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) RegisterDriver(ctx context.Context, in *RegisterDriverRequest, opts ...grpc.CallOption) (*DriverProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverProfile)
	err := c.cc.Invoke(ctx, DeliveryService_RegisterDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetMyDriver(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DriverProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverProfile)
	err := c.cc.Invoke(ctx, DeliveryService_GetMyDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryServiceServer is the server API for DeliveryService service.
// All implementations must embed UnimplementedDeliveryServiceServer
// for forward compatibility.
type DeliveryServiceServer interface {
	AssignDriver(context.Context, *AssignRequest) (*Delivery, error)
	GetDelivery(context.Context, *DeliveryIdRequest) (*Delivery, error)
	UpdateDriverLocation(context.Context, *LocationRequest) (*Empty, error)
	TrackDelivery(context.Context, *DeliveryIdRequest) (*DeliveryStatus, error)
	CompleteDelivery(context.Context, *DeliveryIdRequest) (*Delivery, error)
	ListDriverDeliveries(context.Context, *DriverIdRequest) (*DeliveryList, error)
	GetDeliveryHistory(context.Context, *UserIdRequest) (*DeliveryList, error)
	CancelDelivery(context.Context, *DeliveryIdRequest) (*Delivery, error)
	RegisterDriver(context.Context, *RegisterDriverRequest) (*DriverProfile, error)
	GetMyDriver(context.Context, *Empty) (*DriverProfile, error)
	mustEmbedUnimplementedDeliveryServiceServer()
}

// UnimplementedDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryServiceServer struct{}

func (UnimplementedDeliveryServiceServer) AssignDriver(context.Context, *AssignRequest) (*Delivery, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignDriver not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDelivery(context.Context, *DeliveryIdRequest) (*Delivery, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDelivery not implemented")
}
func (UnimplementedDeliveryServiceServer) UpdateDriverLocation(context.Context, *LocationRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDriverLocation not implemented")
}
func (UnimplementedDeliveryServiceServer) TrackDelivery(context.Context, *DeliveryIdRequest) (*DeliveryStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method TrackDelivery not implemented")
}
func (UnimplementedDeliveryServiceServer) CompleteDelivery(context.Context, *DeliveryIdRequest) (*Delivery, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteDelivery not implemented")
}
func (UnimplementedDeliveryServiceServer) ListDriverDeliveries(context.Context, *DriverIdRequest) (*DeliveryList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDriverDeliveries not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDeliveryHistory(context.Context, *UserIdRequest) (*DeliveryList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveryHistory not implemented")
}
func (UnimplementedDeliveryServiceServer) CancelDelivery(context.Context, *DeliveryIdRequest) (*Delivery, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelDelivery not implemented")
}
func (UnimplementedDeliveryServiceServer) RegisterDriver(context.Context, *RegisterDriverRequest) (*DriverProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDriver not implemented")
}
func (UnimplementedDeliveryServiceServer) GetMyDriver(context.Context, *Empty) (*DriverProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyDriver not implemented")
}
func (UnimplementedDeliveryServiceServer) mustEmbedUnimplementedDeliveryServiceServer() {}
func (UnimplementedDeliveryServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryServiceServer will
// result in compilation errors.
type UnsafeDeliveryServiceServer interface {
	mustEmbedUnimplementedDeliveryServiceServer()
}

func RegisterDeliveryServiceServer(s grpc.ServiceRegistrar, srv DeliveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryService_ServiceDesc, srv)
}

func _DeliveryService_AssignDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).AssignDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_AssignDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).AssignDriver(ctx, req.(*AssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDelivery(ctx, req.(*DeliveryIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_UpdateDriverLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).UpdateDriverLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_UpdateDriverLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).UpdateDriverLocation(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_TrackDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).TrackDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_TrackDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).TrackDelivery(ctx, req.(*DeliveryIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_CompleteDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).CompleteDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_CompleteDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).CompleteDelivery(ctx, req.(*DeliveryIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_ListDriverDeliveries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).ListDriverDeliveries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_ListDriverDeliveries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).ListDriverDeliveries(ctx, req.(*DriverIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetDeliveryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDeliveryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDeliveryHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDeliveryHistory(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_CancelDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).CancelDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_CancelDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).CancelDelivery(ctx, req.(*DeliveryIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_RegisterDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).RegisterDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_RegisterDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).RegisterDriver(ctx, req.(*RegisterDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetMyDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetMyDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetMyDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetMyDriver(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryService_ServiceDesc is the grpc.ServiceDesc for DeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delivery.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignDriver",
			Handler:    _DeliveryService_AssignDriver_Handler,
		},
		{
			MethodName: "GetDelivery",
			Handler:    _DeliveryService_GetDelivery_Handler,
		},
		{
			MethodName: "UpdateDriverLocation",
			Handler:    _DeliveryService_UpdateDriverLocation_Handler,
		},
		{
			MethodName: "TrackDelivery",
			Handler:    _DeliveryService_TrackDelivery_Handler,
		},
		{
			MethodName: "CompleteDelivery",
			Handler:    _DeliveryService_CompleteDelivery_Handler,
		},
		{
			MethodName: "ListDriverDeliveries",
			Handler:    _DeliveryService_ListDriverDeliveries_Handler,
		},
		{
			MethodName: "GetDeliveryHistory",
			Handler:    _DeliveryService_GetDeliveryHistory_Handler,
		},
		{
			MethodName: "CancelDelivery",
			Handler:    _DeliveryService_CancelDelivery_Handler,
		},
		{
			MethodName: "RegisterDriver",
			Handler:    _DeliveryService_RegisterDriver_Handler,
		},
		{
			MethodName: "GetMyDriver",
			Handler:    _DeliveryService_GetMyDriver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery.proto",
}
