// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.0
// source: restaurant.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{0}
}

type RestaurantIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int64                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantIdRequest) Reset() {
	*x = RestaurantIdRequest{}
	mi := &file_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantIdRequest) ProtoMessage() {}

func (x *RestaurantIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantIdRequest.ProtoReflect.Descriptor instead.
func (*RestaurantIdRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *RestaurantIdRequest) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

type MenuItemIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItemIdRequest) Reset() {
	*x = MenuItemIdRequest{}
	mi := &file_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItemIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItemIdRequest) ProtoMessage() {}

func (x *MenuItemIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItemIdRequest.ProtoReflect.Descriptor instead.
func (*MenuItemIdRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{2}
}

func (x *MenuItemIdRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type CreateRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRestaurantRequest) Reset() {
	*x = CreateRestaurantRequest{}
	mi := &file_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantRequest) ProtoMessage() {}

func (x *CreateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*CreateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRestaurantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRestaurantRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRestaurantRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateRestaurantRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateRestaurantRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateRestaurantRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type UpdateRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int64                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRestaurantRequest) Reset() {
	*x = UpdateRestaurantRequest{}
	mi := &file_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRestaurantRequest) ProtoMessage() {}

func (x *UpdateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*UpdateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRestaurantRequest) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *UpdateRestaurantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRestaurantRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRestaurantRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateRestaurantRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateRestaurantRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateRestaurantRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ListRestaurantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // 0 = all categories
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRestaurantsRequest) Reset() {
	*x = ListRestaurantsRequest{}
	mi := &file_restaurant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRestaurantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRestaurantsRequest) ProtoMessage() {}

func (x *ListRestaurantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRestaurantsRequest.ProtoReflect.Descriptor instead.
func (*ListRestaurantsRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{5}
}

func (x *ListRestaurantsRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListRestaurantsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRestaurantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_restaurant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int64                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId    int64                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,5,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Rating        float64                `protobuf:"fixed64,10,opt,name=rating,proto3" json:"rating,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantResponse) Reset() {
	*x = RestaurantResponse{}
	mi := &file_restaurant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantResponse) ProtoMessage() {}

func (x *RestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantResponse.ProtoReflect.Descriptor instead.
func (*RestaurantResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{7}
}

func (x *RestaurantResponse) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *RestaurantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestaurantResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RestaurantResponse) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *RestaurantResponse) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *RestaurantResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RestaurantResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RestaurantResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *RestaurantResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *RestaurantResponse) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *RestaurantResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RestaurantResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RestaurantList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*RestaurantResponse  `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantList) Reset() {
	*x = RestaurantList{}
	mi := &file_restaurant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantList) ProtoMessage() {}

func (x *RestaurantList) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantList.ProtoReflect.Descriptor instead.
func (*RestaurantList) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{8}
}

func (x *RestaurantList) GetRestaurants() []*RestaurantResponse {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

func (x *RestaurantList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int64                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuItemRequest) Reset() {
	*x = CreateMenuItemRequest{}
	mi := &file_restaurant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuItemRequest) ProtoMessage() {}

func (x *CreateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{9}
}

func (x *CreateMenuItemRequest) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *CreateMenuItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMenuItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMenuItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateMenuItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateMenuItemRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type UpdateMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	RestaurantId  int64                  `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,8,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuItemRequest) Reset() {
	*x = UpdateMenuItemRequest{}
	mi := &file_restaurant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemRequest) ProtoMessage() {}

func (x *UpdateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMenuItemRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UpdateMenuItemRequest) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *UpdateMenuItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateMenuItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type MenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	RestaurantId  int64                  `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,8,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItemResponse) Reset() {
	*x = MenuItemResponse{}
	mi := &file_restaurant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItemResponse) ProtoMessage() {}

func (x *MenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItemResponse.ProtoReflect.Descriptor instead.
func (*MenuItemResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{11}
}

func (x *MenuItemResponse) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *MenuItemResponse) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *MenuItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItemResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuItemResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuItemResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MenuItemResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *MenuItemResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *MenuItemResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MenuItemResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MenuList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItemResponse    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuList) Reset() {
	*x = MenuList{}
	mi := &file_restaurant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuList) ProtoMessage() {}

func (x *MenuList) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuList.ProtoReflect.Descriptor instead.
func (*MenuList) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{12}
}

func (x *MenuList) GetItems() []*MenuItemResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_restaurant_proto protoreflect.FileDescriptor

const file_restaurant_proto_rawDesc = "" +
	"\n" +
	"\x10restaurant.proto\x12\n" +
	"restaurant\"\a\n" +
	"\x05Empty\":\n" +
	"\x13RestaurantIdRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x03R\frestaurantId\",\n" +
	"\x11MenuItemIdRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\"\xbd\x01\n" +
	"\x17CreateRestaurantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\"\xde\x01\n" +
	"\x17UpdateRestaurantRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x03R\frestaurantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"j\n" +
	"\x16ListRestaurantsRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"V\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xf5\x02\n" +
	"\x12RestaurantResponse\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x03R\frestaurantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x05 \x01(\tR\fcategoryName\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12\x16\n" +
	"\x06rating\x18\n" +
	" \x01(\x01R\x06rating\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"h\n" +
	"\x0eRestaurantList\x12@\n" +
	"\vrestaurants\x18\x01 \x03(\v2\x1e.restaurant.RestaurantResponseR\vrestaurants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xc1\x01\n" +
	"\x15CreateMenuItemRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x03R\frestaurantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\"\xfd\x01\n" +
	"\x15UpdateMenuItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\x03R\frestaurantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12!\n" +
	"\fis_available\x18\b \x01(\bR\visAvailable\"\xb6\x02\n" +
	"\x10MenuItemResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\x03R\frestaurantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12!\n" +
	"\fis_available\x18\b \x01(\bR\visAvailable\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\">\n" +
	"\bMenuList\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.restaurant.MenuItemResponseR\x05items2\xaa\x06\n" +
	"\x11RestaurantService\x12W\n" +
	"\x10CreateRestaurant\x12#.restaurant.CreateRestaurantRequest\x1a\x1e.restaurant.RestaurantResponse\x12P\n" +
	"\rGetRestaurant\x12\x1f.restaurant.RestaurantIdRequest\x1a\x1e.restaurant.RestaurantResponse\x12Q\n" +
	"\x0fListRestaurants\x12\".restaurant.ListRestaurantsRequest\x1a\x1a.restaurant.RestaurantList\x12J\n" +
	"\x11SearchRestaurants\x12\x19.restaurant.SearchRequest\x1a\x1a.restaurant.RestaurantList\x12W\n" +
	"\x10UpdateRestaurant\x12#.restaurant.UpdateRestaurantRequest\x1a\x1e.restaurant.RestaurantResponse\x12F\n" +
	"\x10DeleteRestaurant\x12\x1f.restaurant.RestaurantIdRequest\x1a\x11.restaurant.Empty\x12Q\n" +
	"\x0eCreateMenuItem\x12!.restaurant.CreateMenuItemRequest\x1a\x1c.restaurant.MenuItemResponse\x12Q\n" +
	"\x0eUpdateMenuItem\x12!.restaurant.UpdateMenuItemRequest\x1a\x1c.restaurant.MenuItemResponse\x12B\n" +
	"\x0eDeleteMenuItem\x12\x1d.restaurant.MenuItemIdRequest\x1a\x11.restaurant.Empty\x12@\n" +
	"\aGetMenu\x12\x1f.restaurant.RestaurantIdRequest\x1a\x14.restaurant.MenuListB+Z)food-delivery/restaurant-service/proto/pbb\x06proto3"

var (
	file_restaurant_proto_rawDescOnce sync.Once
	file_restaurant_proto_rawDescData []byte
)

func file_restaurant_proto_rawDescGZIP() []byte {
	file_restaurant_proto_rawDescOnce.Do(func() {
		file_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restaurant_proto_rawDesc), len(file_restaurant_proto_rawDesc)))
	})
	return file_restaurant_proto_rawDescData
}

var file_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_restaurant_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: restaurant.Empty
	(*RestaurantIdRequest)(nil),     // 1: restaurant.RestaurantIdRequest
	(*MenuItemIdRequest)(nil),       // 2: restaurant.MenuItemIdRequest
	(*CreateRestaurantRequest)(nil), // 3: restaurant.CreateRestaurantRequest
	(*UpdateRestaurantRequest)(nil), // 4: restaurant.UpdateRestaurantRequest
	(*ListRestaurantsRequest)(nil),  // 5: restaurant.ListRestaurantsRequest
	(*SearchRequest)(nil),           // 6: restaurant.SearchRequest
	(*RestaurantResponse)(nil),      // 7: restaurant.RestaurantResponse
	(*RestaurantList)(nil),          // 8: restaurant.RestaurantList
	(*CreateMenuItemRequest)(nil),   // 9: restaurant.CreateMenuItemRequest
	(*UpdateMenuItemRequest)(nil),   // 10: restaurant.UpdateMenuItemRequest
	(*MenuItemResponse)(nil),        // 11: restaurant.MenuItemResponse
	(*MenuList)(nil),                // 12: restaurant.MenuList
}
var file_restaurant_proto_depIdxs = []int32{
	7,  // 0: restaurant.RestaurantList.restaurants:type_name -> restaurant.RestaurantResponse
	11, // 1: restaurant.MenuList.items:type_name -> restaurant.MenuItemResponse
	3,  // 2: restaurant.RestaurantService.CreateRestaurant:input_type -> restaurant.CreateRestaurantRequest
	1,  // 3: restaurant.RestaurantService.GetRestaurant:input_type -> restaurant.RestaurantIdRequest
	5,  // 4: restaurant.RestaurantService.ListRestaurants:input_type -> restaurant.ListRestaurantsRequest
	6,  // 5: restaurant.RestaurantService.SearchRestaurants:input_type -> restaurant.SearchRequest
	4,  // 6: restaurant.RestaurantService.UpdateRestaurant:input_type -> restaurant.UpdateRestaurantRequest
	1,  // 7: restaurant.RestaurantService.DeleteRestaurant:input_type -> restaurant.RestaurantIdRequest
	9,  // 8: restaurant.RestaurantService.CreateMenuItem:input_type -> restaurant.CreateMenuItemRequest
	10, // 9: restaurant.RestaurantService.UpdateMenuItem:input_type -> restaurant.UpdateMenuItemRequest
	2,  // 10: restaurant.RestaurantService.DeleteMenuItem:input_type -> restaurant.MenuItemIdRequest
	1,  // 11: restaurant.RestaurantService.GetMenu:input_type -> restaurant.RestaurantIdRequest
	7,  // 12: restaurant.RestaurantService.CreateRestaurant:output_type -> restaurant.RestaurantResponse
	7,  // 13: restaurant.RestaurantService.GetRestaurant:output_type -> restaurant.RestaurantResponse
	8,  // 14: restaurant.RestaurantService.ListRestaurants:output_type -> restaurant.RestaurantList
	8,  // 15: restaurant.RestaurantService.SearchRestaurants:output_type -> restaurant.RestaurantList
	7,  // 16: restaurant.RestaurantService.UpdateRestaurant:output_type -> restaurant.RestaurantResponse
	0,  // 17: restaurant.RestaurantService.DeleteRestaurant:output_type -> restaurant.Empty
	11, // 18: restaurant.RestaurantService.CreateMenuItem:output_type -> restaurant.MenuItemResponse
	11, // 19: restaurant.RestaurantService.UpdateMenuItem:output_type -> restaurant.MenuItemResponse
	0,  // 20: restaurant.RestaurantService.DeleteMenuItem:output_type -> restaurant.Empty
	12, // 21: restaurant.RestaurantService.GetMenu:output_type -> restaurant.MenuList
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_restaurant_proto_init() }
func file_restaurant_proto_init() {
	if File_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restaurant_proto_rawDesc), len(file_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restaurant_proto_goTypes,
		DependencyIndexes: file_restaurant_proto_depIdxs,
		MessageInfos:      file_restaurant_proto_msgTypes,
	}.Build()
	File_restaurant_proto = out.File
	file_restaurant_proto_goTypes = nil
	file_restaurant_proto_depIdxs = nil
}
